name: "CI Build - Ramadan Test"

on:
  push:
    branches:
      - ramadan-test  # Trigger on your specific branch
  workflow_dispatch:  # Allow manual trigger

env:
  PC_VERSION: "3.2.3"
  RGBDS_VERSION: "v1.0.1"

jobs:
  build-ubuntu:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - id: set-env-var
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - id: apt-get-depends
        run: |
          sudo apt-get update
          sudo apt-get install bison gcc git make libpng-dev -y;

      - id: checkout-rgbds
        uses: actions/checkout@v4
        with:
          path: rgbds
          ref: ${{ env.RGBDS_VERSION }}
          repository: gbdev/rgbds

      - id: install-rgbds
        working-directory: rgbds
        run: sudo make install

      - id: checkout-polishedcrystal
        uses: actions/checkout@v4

      - id: build-polishedcrystal-faithful
        name: "Build Faithful ROM"
        run: |
          mkdir build
          make -j$(nproc) faithful
          mv polishedcrystal-faithful-${{ env.PC_VERSION }}.gbc build/faithful-rom.gbc
          # We only build the faithful one to save time

      - id: upload-polishedcrystal
        name: "Upload My ROM"
        uses: actions/upload-artifact@v4
        with:
          name: "polished-faithful-rom"
          path: build/faithful-rom.gbc
